config/routes.rb
Rails.application.routes.draw do
  
  resources :payments
  resources :products
  resources :invoices do
    resources :items
  end
  get 'welcome/index'
  root 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many:items
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @products = Product.all
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:total, :created, :exp_date)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total, :value=>0 %>
  </div>

  <%= form.hidden_field :created %>
  <div class="field">
    <%= form.label :"Fecha Vencimiento" %><br>
    <%= form.datetime_select :exp_date %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facturas</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th>Creada</th>
      <th>Vence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td>$<%= invoice.total %></td>
        <td><%= invoice.created.to_formatted_s(:short) %></td>
        <td><%= invoice.exp_date.to_formatted_s(:short) %></td>
        <td><%= link_to 'Pagar', new_payment_path(:invoice_id=>invoice) %></td>
        <td><%= link_to 'Ver', invoice %></td>
        <td><%= link_to 'Editar', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Borrar', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>Nueva Factura</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @invoice.total %>
</p>

<p>
  <strong>Created:</strong>
  <%= @invoice.created %>
</p>

<p>
  <strong>Exp date:</strong>
  <%= @invoice.exp_date %>
</p>

<hr/>

<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Invoice</th>
      <th>Quantity</th>
      <th>Price</th> 
    </tr>
  </thead>
  <tbody>
  <% @invoice.items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.invoice_id %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Agregar Conceptos</h3>
<%= form_for([@invoice, @invoice.items.build]) do |f| %>
  <%= f.hidden_field :invoice_id, :value=>@invoice.id %>
  <div class="field">
    <%= f.label :"Producto" %>
    <%= f.select(:product_id ,Product.pluck(:name, :id)) %>
  </div>
  <div class="field">
    <%= f.label :"Cantidad" %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :"Precio" %>
    <%= f.text_field :price %>
  </div>
  <p>
    <%= f.submit %> 
  </p>
<% end %>
<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>